function [MSD,ACF]=Gen_Maxwell_fun(t,Omega,Gamma,Tau_m,Tau_p)
%Analytic espression for the normalized ACF & MSD of a single-relaxation Maxwell fluid.

if imag(Omega) == 0
    Omega = abs(Omega);
    ACF = (cos(Omega*t) + (1/(2*Omega))*(1/Tau_m - 1/Tau_p)*sin(Omega*t)).*exp(-Gamma*t);
    MSD = 1/(Tau_p * Tau_m * Omega * (Gamma^2 + Omega^2)^2)* ...
        (...
            Omega*(Gamma*(2-t*Gamma)*Tau_m + Gamma*(-2+t*Gamma+2*Gamma*(-1+t*Gamma)*Tau_m)*Tau_p + (-t*Tau_m+(t+2*Tau_m+2*t*Gamma*Tau_m)*Tau_p)*Omega^2) + ...
            exp(-t*Gamma).*(...
                2*Omega*(Gamma*(Tau_p+Tau_m*(-1+Gamma*Tau_p))-Tau_m*Tau_p*Omega^2)*cos(Omega*t) + ...
                (Gamma^2*(-Tau_m+Tau_p)+(Tau_m-Tau_p-4*Gamma*Tau_m*Tau_p)*Omega^2)*sin(Omega*t) ...
            )...
        );
else
    Omega = abs(Omega);
    Damp_p = Gamma + Omega;
    Damp_m = Gamma - Omega;
    ACF = (0.5/Omega) * ((Damp_p - 1/Tau_p)*exp(-Damp_m*t) - (Damp_m - 1/Tau_p)*exp(-Damp_p*t));
    MSD = (1/(Tau_p * Omega * (Gamma^2 - Omega^2)^2))*(...
     + Tau_p*Omega*(...
        Gamma^2*(-6 + 3*exp(-t*(Gamma + Omega)) +  3*exp(t*(Omega-Gamma)) + 4*t*Gamma) + ...
        Gamma*Omega*(-3*exp(-t*(Omega + Gamma)) + 3*exp(t*(Omega-Gamma))) + ...
        Omega^2*(-2 + exp(-t*(Gamma + Omega)) + exp(t*(Omega-Gamma)) - 4*t*Gamma)...
    )...
    + Omega*(...
        Gamma*(4 - 2*exp(-t*(Gamma + Omega)) - 2*exp(t*(Omega-Gamma)) - 2*t*Gamma) + ...
        Omega*(exp(-t*(Gamma + Omega)) - exp(t*(Omega-Gamma)) + 2*t*Omega)...
    )...
    + Tau_p*Gamma^3*(-exp(-t*(Gamma + Omega)) + exp(t*(Omega-Gamma))) ...
    + Gamma^2*(exp(-t*(Gamma + Omega)) - exp(t*(Omega-Gamma)))...
    );
    %Alternative  
    %MSDDWS = zeros(length(t),1);
    %for i = 1:length(MSDDWS)
    %    MSDDWS(i) = MSD_Maxwell_fun(t(i),Omega,Gamma,Tau_p);
    %end
end
        
