function bpimg = FD_2D_prep_2a(img,upbp,thresh)

bpimg = bpass(img,1,upbp);
    
bpimg = (bpimg > thresh).*255;
    
sub(:,1) = [sort(repmat([1:upbp],1,size(bpimg,2))) repmat([1: ...
                    size(bpimg,1)],1,upbp) sort(repmat([size(bpimg, ...
                                                  1)-upbp: ...
                    size(bpimg,1)],1,size(bpimg,2))) repmat([1: ...
                    size(bpimg,1)],1,upbp)];
sub(:,2) = [repmat([1:size(bpimg,2)],1,upbp) sort(repmat([1: ...
                    upbp],1,size(bpimg,1))) repmat([1: size(bpimg, ...
                                                  2)],1,upbp) ...
            sort(repmat([size(bpimg,2)-upbp:size(bpimg,1)],1, size(bpimg,1)))];
ind = sub2ind(size(bpimg),sub(:,1),sub(:,2)); 
foo = bpimg;
foo(ind) = (img(ind) > mean(mean(img))).*255;
bpimg = imfill(foo,'holes');
bpimg(ind) = 0;